// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mdt_grpc_dialin.proto

package IOSXRExtensibleManagabilityService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommitResult int32

const (
	CommitResult_CHANGE    CommitResult = 0
	CommitResult_NO_CHANGE CommitResult = 1
	CommitResult_FAIL      CommitResult = 2
)

var CommitResult_name = map[int32]string{
	0: "CHANGE",
	1: "NO_CHANGE",
	2: "FAIL",
}

var CommitResult_value = map[string]int32{
	"CHANGE":    0,
	"NO_CHANGE": 1,
	"FAIL":      2,
}

func (x CommitResult) String() string {
	return proto.EnumName(CommitResult_name, int32(x))
}

func (CommitResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{0}
}

type ConfigGetArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Yangpathjson         string   `protobuf:"bytes,2,opt,name=yangpathjson,proto3" json:"yangpathjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigGetArgs) Reset()         { *m = ConfigGetArgs{} }
func (m *ConfigGetArgs) String() string { return proto.CompactTextString(m) }
func (*ConfigGetArgs) ProtoMessage()    {}
func (*ConfigGetArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{0}
}

func (m *ConfigGetArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetArgs.Unmarshal(m, b)
}
func (m *ConfigGetArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetArgs.Marshal(b, m, deterministic)
}
func (m *ConfigGetArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetArgs.Merge(m, src)
}
func (m *ConfigGetArgs) XXX_Size() int {
	return xxx_messageInfo_ConfigGetArgs.Size(m)
}
func (m *ConfigGetArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetArgs proto.InternalMessageInfo

func (m *ConfigGetArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ConfigGetArgs) GetYangpathjson() string {
	if m != nil {
		return m.Yangpathjson
	}
	return ""
}

type ConfigGetReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Yangjson             string   `protobuf:"bytes,2,opt,name=yangjson,proto3" json:"yangjson,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigGetReply) Reset()         { *m = ConfigGetReply{} }
func (m *ConfigGetReply) String() string { return proto.CompactTextString(m) }
func (*ConfigGetReply) ProtoMessage()    {}
func (*ConfigGetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{1}
}

func (m *ConfigGetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetReply.Unmarshal(m, b)
}
func (m *ConfigGetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetReply.Marshal(b, m, deterministic)
}
func (m *ConfigGetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetReply.Merge(m, src)
}
func (m *ConfigGetReply) XXX_Size() int {
	return xxx_messageInfo_ConfigGetReply.Size(m)
}
func (m *ConfigGetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetReply proto.InternalMessageInfo

func (m *ConfigGetReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *ConfigGetReply) GetYangjson() string {
	if m != nil {
		return m.Yangjson
	}
	return ""
}

func (m *ConfigGetReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type GetOperArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Yangpathjson         string   `protobuf:"bytes,2,opt,name=yangpathjson,proto3" json:"yangpathjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperArgs) Reset()         { *m = GetOperArgs{} }
func (m *GetOperArgs) String() string { return proto.CompactTextString(m) }
func (*GetOperArgs) ProtoMessage()    {}
func (*GetOperArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{2}
}

func (m *GetOperArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperArgs.Unmarshal(m, b)
}
func (m *GetOperArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperArgs.Marshal(b, m, deterministic)
}
func (m *GetOperArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperArgs.Merge(m, src)
}
func (m *GetOperArgs) XXX_Size() int {
	return xxx_messageInfo_GetOperArgs.Size(m)
}
func (m *GetOperArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperArgs proto.InternalMessageInfo

func (m *GetOperArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *GetOperArgs) GetYangpathjson() string {
	if m != nil {
		return m.Yangpathjson
	}
	return ""
}

type GetOperReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Yangjson             string   `protobuf:"bytes,2,opt,name=yangjson,proto3" json:"yangjson,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperReply) Reset()         { *m = GetOperReply{} }
func (m *GetOperReply) String() string { return proto.CompactTextString(m) }
func (*GetOperReply) ProtoMessage()    {}
func (*GetOperReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{3}
}

func (m *GetOperReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperReply.Unmarshal(m, b)
}
func (m *GetOperReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperReply.Marshal(b, m, deterministic)
}
func (m *GetOperReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperReply.Merge(m, src)
}
func (m *GetOperReply) XXX_Size() int {
	return xxx_messageInfo_GetOperReply.Size(m)
}
func (m *GetOperReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperReply proto.InternalMessageInfo

func (m *GetOperReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *GetOperReply) GetYangjson() string {
	if m != nil {
		return m.Yangjson
	}
	return ""
}

func (m *GetOperReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type ConfigArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Yangjson             string   `protobuf:"bytes,2,opt,name=yangjson,proto3" json:"yangjson,omitempty"`
	Confirmed            bool     `protobuf:"varint,3,opt,name=Confirmed,proto3" json:"Confirmed,omitempty"`
	ConfirmTimeout       uint32   `protobuf:"varint,4,opt,name=ConfirmTimeout,proto3" json:"ConfirmTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigArgs) Reset()         { *m = ConfigArgs{} }
func (m *ConfigArgs) String() string { return proto.CompactTextString(m) }
func (*ConfigArgs) ProtoMessage()    {}
func (*ConfigArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{4}
}

func (m *ConfigArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigArgs.Unmarshal(m, b)
}
func (m *ConfigArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigArgs.Marshal(b, m, deterministic)
}
func (m *ConfigArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigArgs.Merge(m, src)
}
func (m *ConfigArgs) XXX_Size() int {
	return xxx_messageInfo_ConfigArgs.Size(m)
}
func (m *ConfigArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigArgs proto.InternalMessageInfo

func (m *ConfigArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ConfigArgs) GetYangjson() string {
	if m != nil {
		return m.Yangjson
	}
	return ""
}

func (m *ConfigArgs) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *ConfigArgs) GetConfirmTimeout() uint32 {
	if m != nil {
		return m.ConfirmTimeout
	}
	return 0
}

type ConfigReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Errors               string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	CommitID             uint32   `protobuf:"varint,3,opt,name=CommitID,proto3" json:"CommitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigReply) Reset()         { *m = ConfigReply{} }
func (m *ConfigReply) String() string { return proto.CompactTextString(m) }
func (*ConfigReply) ProtoMessage()    {}
func (*ConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{5}
}

func (m *ConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigReply.Unmarshal(m, b)
}
func (m *ConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigReply.Marshal(b, m, deterministic)
}
func (m *ConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigReply.Merge(m, src)
}
func (m *ConfigReply) XXX_Size() int {
	return xxx_messageInfo_ConfigReply.Size(m)
}
func (m *ConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigReply proto.InternalMessageInfo

func (m *ConfigReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *ConfigReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func (m *ConfigReply) GetCommitID() uint32 {
	if m != nil {
		return m.CommitID
	}
	return 0
}

type CliConfigArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Cli                  string   `protobuf:"bytes,2,opt,name=cli,proto3" json:"cli,omitempty"`
	Confirmed            bool     `protobuf:"varint,3,opt,name=Confirmed,proto3" json:"Confirmed,omitempty"`
	ConfirmTimeout       uint32   `protobuf:"varint,4,opt,name=ConfirmTimeout,proto3" json:"ConfirmTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliConfigArgs) Reset()         { *m = CliConfigArgs{} }
func (m *CliConfigArgs) String() string { return proto.CompactTextString(m) }
func (*CliConfigArgs) ProtoMessage()    {}
func (*CliConfigArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{6}
}

func (m *CliConfigArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliConfigArgs.Unmarshal(m, b)
}
func (m *CliConfigArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliConfigArgs.Marshal(b, m, deterministic)
}
func (m *CliConfigArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliConfigArgs.Merge(m, src)
}
func (m *CliConfigArgs) XXX_Size() int {
	return xxx_messageInfo_CliConfigArgs.Size(m)
}
func (m *CliConfigArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CliConfigArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CliConfigArgs proto.InternalMessageInfo

func (m *CliConfigArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *CliConfigArgs) GetCli() string {
	if m != nil {
		return m.Cli
	}
	return ""
}

func (m *CliConfigArgs) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *CliConfigArgs) GetConfirmTimeout() uint32 {
	if m != nil {
		return m.ConfirmTimeout
	}
	return 0
}

type CliConfigReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Errors               string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	CommitID             uint32   `protobuf:"varint,3,opt,name=CommitID,proto3" json:"CommitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliConfigReply) Reset()         { *m = CliConfigReply{} }
func (m *CliConfigReply) String() string { return proto.CompactTextString(m) }
func (*CliConfigReply) ProtoMessage()    {}
func (*CliConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{7}
}

func (m *CliConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliConfigReply.Unmarshal(m, b)
}
func (m *CliConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliConfigReply.Marshal(b, m, deterministic)
}
func (m *CliConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliConfigReply.Merge(m, src)
}
func (m *CliConfigReply) XXX_Size() int {
	return xxx_messageInfo_CliConfigReply.Size(m)
}
func (m *CliConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CliConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_CliConfigReply proto.InternalMessageInfo

func (m *CliConfigReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *CliConfigReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func (m *CliConfigReply) GetCommitID() uint32 {
	if m != nil {
		return m.CommitID
	}
	return 0
}

type CommitReplaceArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Cli                  string   `protobuf:"bytes,2,opt,name=cli,proto3" json:"cli,omitempty"`
	Yangjson             string   `protobuf:"bytes,3,opt,name=yangjson,proto3" json:"yangjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitReplaceArgs) Reset()         { *m = CommitReplaceArgs{} }
func (m *CommitReplaceArgs) String() string { return proto.CompactTextString(m) }
func (*CommitReplaceArgs) ProtoMessage()    {}
func (*CommitReplaceArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{8}
}

func (m *CommitReplaceArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReplaceArgs.Unmarshal(m, b)
}
func (m *CommitReplaceArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReplaceArgs.Marshal(b, m, deterministic)
}
func (m *CommitReplaceArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReplaceArgs.Merge(m, src)
}
func (m *CommitReplaceArgs) XXX_Size() int {
	return xxx_messageInfo_CommitReplaceArgs.Size(m)
}
func (m *CommitReplaceArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReplaceArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReplaceArgs proto.InternalMessageInfo

func (m *CommitReplaceArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *CommitReplaceArgs) GetCli() string {
	if m != nil {
		return m.Cli
	}
	return ""
}

func (m *CommitReplaceArgs) GetYangjson() string {
	if m != nil {
		return m.Yangjson
	}
	return ""
}

type CommitReplaceReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Errors               string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitReplaceReply) Reset()         { *m = CommitReplaceReply{} }
func (m *CommitReplaceReply) String() string { return proto.CompactTextString(m) }
func (*CommitReplaceReply) ProtoMessage()    {}
func (*CommitReplaceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{9}
}

func (m *CommitReplaceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReplaceReply.Unmarshal(m, b)
}
func (m *CommitReplaceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReplaceReply.Marshal(b, m, deterministic)
}
func (m *CommitReplaceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReplaceReply.Merge(m, src)
}
func (m *CommitReplaceReply) XXX_Size() int {
	return xxx_messageInfo_CommitReplaceReply.Size(m)
}
func (m *CommitReplaceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReplaceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReplaceReply proto.InternalMessageInfo

func (m *CommitReplaceReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *CommitReplaceReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type CommitMsg struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitMsg) Reset()         { *m = CommitMsg{} }
func (m *CommitMsg) String() string { return proto.CompactTextString(m) }
func (*CommitMsg) ProtoMessage()    {}
func (*CommitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{10}
}

func (m *CommitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitMsg.Unmarshal(m, b)
}
func (m *CommitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitMsg.Marshal(b, m, deterministic)
}
func (m *CommitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitMsg.Merge(m, src)
}
func (m *CommitMsg) XXX_Size() int {
	return xxx_messageInfo_CommitMsg.Size(m)
}
func (m *CommitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CommitMsg proto.InternalMessageInfo

func (m *CommitMsg) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *CommitMsg) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type CommitArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	CommitID             uint32   `protobuf:"varint,2,opt,name=CommitID,proto3" json:"CommitID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitArgs) Reset()         { *m = CommitArgs{} }
func (m *CommitArgs) String() string { return proto.CompactTextString(m) }
func (*CommitArgs) ProtoMessage()    {}
func (*CommitArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{11}
}

func (m *CommitArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitArgs.Unmarshal(m, b)
}
func (m *CommitArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitArgs.Marshal(b, m, deterministic)
}
func (m *CommitArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitArgs.Merge(m, src)
}
func (m *CommitArgs) XXX_Size() int {
	return xxx_messageInfo_CommitArgs.Size(m)
}
func (m *CommitArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CommitArgs proto.InternalMessageInfo

func (m *CommitArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *CommitArgs) GetCommitID() uint32 {
	if m != nil {
		return m.CommitID
	}
	return 0
}

type CommitReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Errors               string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitReply) Reset()         { *m = CommitReply{} }
func (m *CommitReply) String() string { return proto.CompactTextString(m) }
func (*CommitReply) ProtoMessage()    {}
func (*CommitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{12}
}

func (m *CommitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReply.Unmarshal(m, b)
}
func (m *CommitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReply.Marshal(b, m, deterministic)
}
func (m *CommitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReply.Merge(m, src)
}
func (m *CommitReply) XXX_Size() int {
	return xxx_messageInfo_CommitReply.Size(m)
}
func (m *CommitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReply.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReply proto.InternalMessageInfo

func (m *CommitReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *CommitReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type DiscardChangesArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardChangesArgs) Reset()         { *m = DiscardChangesArgs{} }
func (m *DiscardChangesArgs) String() string { return proto.CompactTextString(m) }
func (*DiscardChangesArgs) ProtoMessage()    {}
func (*DiscardChangesArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{13}
}

func (m *DiscardChangesArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardChangesArgs.Unmarshal(m, b)
}
func (m *DiscardChangesArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardChangesArgs.Marshal(b, m, deterministic)
}
func (m *DiscardChangesArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardChangesArgs.Merge(m, src)
}
func (m *DiscardChangesArgs) XXX_Size() int {
	return xxx_messageInfo_DiscardChangesArgs.Size(m)
}
func (m *DiscardChangesArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardChangesArgs.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardChangesArgs proto.InternalMessageInfo

func (m *DiscardChangesArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type DiscardChangesReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Errors               string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscardChangesReply) Reset()         { *m = DiscardChangesReply{} }
func (m *DiscardChangesReply) String() string { return proto.CompactTextString(m) }
func (*DiscardChangesReply) ProtoMessage()    {}
func (*DiscardChangesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{14}
}

func (m *DiscardChangesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscardChangesReply.Unmarshal(m, b)
}
func (m *DiscardChangesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscardChangesReply.Marshal(b, m, deterministic)
}
func (m *DiscardChangesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscardChangesReply.Merge(m, src)
}
func (m *DiscardChangesReply) XXX_Size() int {
	return xxx_messageInfo_DiscardChangesReply.Size(m)
}
func (m *DiscardChangesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscardChangesReply.DiscardUnknown(m)
}

var xxx_messageInfo_DiscardChangesReply proto.InternalMessageInfo

func (m *DiscardChangesReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *DiscardChangesReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type ShowCmdArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Cli                  string   `protobuf:"bytes,2,opt,name=cli,proto3" json:"cli,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowCmdArgs) Reset()         { *m = ShowCmdArgs{} }
func (m *ShowCmdArgs) String() string { return proto.CompactTextString(m) }
func (*ShowCmdArgs) ProtoMessage()    {}
func (*ShowCmdArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{15}
}

func (m *ShowCmdArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCmdArgs.Unmarshal(m, b)
}
func (m *ShowCmdArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCmdArgs.Marshal(b, m, deterministic)
}
func (m *ShowCmdArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCmdArgs.Merge(m, src)
}
func (m *ShowCmdArgs) XXX_Size() int {
	return xxx_messageInfo_ShowCmdArgs.Size(m)
}
func (m *ShowCmdArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCmdArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCmdArgs proto.InternalMessageInfo

func (m *ShowCmdArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ShowCmdArgs) GetCli() string {
	if m != nil {
		return m.Cli
	}
	return ""
}

type ShowCmdTextReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowCmdTextReply) Reset()         { *m = ShowCmdTextReply{} }
func (m *ShowCmdTextReply) String() string { return proto.CompactTextString(m) }
func (*ShowCmdTextReply) ProtoMessage()    {}
func (*ShowCmdTextReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{16}
}

func (m *ShowCmdTextReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCmdTextReply.Unmarshal(m, b)
}
func (m *ShowCmdTextReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCmdTextReply.Marshal(b, m, deterministic)
}
func (m *ShowCmdTextReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCmdTextReply.Merge(m, src)
}
func (m *ShowCmdTextReply) XXX_Size() int {
	return xxx_messageInfo_ShowCmdTextReply.Size(m)
}
func (m *ShowCmdTextReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCmdTextReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCmdTextReply proto.InternalMessageInfo

func (m *ShowCmdTextReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *ShowCmdTextReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *ShowCmdTextReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type ShowCmdJSONReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Jsonoutput           string   `protobuf:"bytes,2,opt,name=jsonoutput,proto3" json:"jsonoutput,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowCmdJSONReply) Reset()         { *m = ShowCmdJSONReply{} }
func (m *ShowCmdJSONReply) String() string { return proto.CompactTextString(m) }
func (*ShowCmdJSONReply) ProtoMessage()    {}
func (*ShowCmdJSONReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{17}
}

func (m *ShowCmdJSONReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowCmdJSONReply.Unmarshal(m, b)
}
func (m *ShowCmdJSONReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowCmdJSONReply.Marshal(b, m, deterministic)
}
func (m *ShowCmdJSONReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowCmdJSONReply.Merge(m, src)
}
func (m *ShowCmdJSONReply) XXX_Size() int {
	return xxx_messageInfo_ShowCmdJSONReply.Size(m)
}
func (m *ShowCmdJSONReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowCmdJSONReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowCmdJSONReply proto.InternalMessageInfo

func (m *ShowCmdJSONReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *ShowCmdJSONReply) GetJsonoutput() string {
	if m != nil {
		return m.Jsonoutput
	}
	return ""
}

func (m *ShowCmdJSONReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

// QOSMarking specifies the DSCP value to be set on transmitted telemetry
type QOSMarking struct {
	Marking              uint32   `protobuf:"varint,1,opt,name=marking,proto3" json:"marking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QOSMarking) Reset()         { *m = QOSMarking{} }
func (m *QOSMarking) String() string { return proto.CompactTextString(m) }
func (*QOSMarking) ProtoMessage()    {}
func (*QOSMarking) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{18}
}

func (m *QOSMarking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QOSMarking.Unmarshal(m, b)
}
func (m *QOSMarking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QOSMarking.Marshal(b, m, deterministic)
}
func (m *QOSMarking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QOSMarking.Merge(m, src)
}
func (m *QOSMarking) XXX_Size() int {
	return xxx_messageInfo_QOSMarking.Size(m)
}
func (m *QOSMarking) XXX_DiscardUnknown() {
	xxx_messageInfo_QOSMarking.DiscardUnknown(m)
}

var xxx_messageInfo_QOSMarking proto.InternalMessageInfo

func (m *QOSMarking) GetMarking() uint32 {
	if m != nil {
		return m.Marking
	}
	return 0
}

// Valid encode values- gpb:2, self-describing-gpb:3, json:4
type CreateSubsArgs struct {
	ReqId                int64       `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Encode               int64       `protobuf:"varint,2,opt,name=encode,proto3" json:"encode,omitempty"`
	Subidstr             string      `protobuf:"bytes,3,opt,name=subidstr,proto3" json:"subidstr,omitempty"`
	Qos                  *QOSMarking `protobuf:"bytes,4,opt,name=qos,proto3" json:"qos,omitempty"`
	Subscriptions        []string    `protobuf:"bytes,5,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSubsArgs) Reset()         { *m = CreateSubsArgs{} }
func (m *CreateSubsArgs) String() string { return proto.CompactTextString(m) }
func (*CreateSubsArgs) ProtoMessage()    {}
func (*CreateSubsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{19}
}

func (m *CreateSubsArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubsArgs.Unmarshal(m, b)
}
func (m *CreateSubsArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubsArgs.Marshal(b, m, deterministic)
}
func (m *CreateSubsArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubsArgs.Merge(m, src)
}
func (m *CreateSubsArgs) XXX_Size() int {
	return xxx_messageInfo_CreateSubsArgs.Size(m)
}
func (m *CreateSubsArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubsArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubsArgs proto.InternalMessageInfo

func (m *CreateSubsArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *CreateSubsArgs) GetEncode() int64 {
	if m != nil {
		return m.Encode
	}
	return 0
}

func (m *CreateSubsArgs) GetSubidstr() string {
	if m != nil {
		return m.Subidstr
	}
	return ""
}

func (m *CreateSubsArgs) GetQos() *QOSMarking {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *CreateSubsArgs) GetSubscriptions() []string {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type CreateSubsReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubsReply) Reset()         { *m = CreateSubsReply{} }
func (m *CreateSubsReply) String() string { return proto.CompactTextString(m) }
func (*CreateSubsReply) ProtoMessage()    {}
func (*CreateSubsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{20}
}

func (m *CreateSubsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubsReply.Unmarshal(m, b)
}
func (m *CreateSubsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubsReply.Marshal(b, m, deterministic)
}
func (m *CreateSubsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubsReply.Merge(m, src)
}
func (m *CreateSubsReply) XXX_Size() int {
	return xxx_messageInfo_CreateSubsReply.Size(m)
}
func (m *CreateSubsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubsReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubsReply proto.InternalMessageInfo

func (m *CreateSubsReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *CreateSubsReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateSubsReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type ActionJSONArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	Yangpathjson         string   `protobuf:"bytes,2,opt,name=yangpathjson,proto3" json:"yangpathjson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionJSONArgs) Reset()         { *m = ActionJSONArgs{} }
func (m *ActionJSONArgs) String() string { return proto.CompactTextString(m) }
func (*ActionJSONArgs) ProtoMessage()    {}
func (*ActionJSONArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{21}
}

func (m *ActionJSONArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionJSONArgs.Unmarshal(m, b)
}
func (m *ActionJSONArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionJSONArgs.Marshal(b, m, deterministic)
}
func (m *ActionJSONArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionJSONArgs.Merge(m, src)
}
func (m *ActionJSONArgs) XXX_Size() int {
	return xxx_messageInfo_ActionJSONArgs.Size(m)
}
func (m *ActionJSONArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionJSONArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ActionJSONArgs proto.InternalMessageInfo

func (m *ActionJSONArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ActionJSONArgs) GetYangpathjson() string {
	if m != nil {
		return m.Yangpathjson
	}
	return ""
}

type ActionJSONReply struct {
	ResReqId             int64    `protobuf:"varint,1,opt,name=ResReqId,proto3" json:"ResReqId,omitempty"`
	Yangjson             string   `protobuf:"bytes,2,opt,name=yangjson,proto3" json:"yangjson,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionJSONReply) Reset()         { *m = ActionJSONReply{} }
func (m *ActionJSONReply) String() string { return proto.CompactTextString(m) }
func (*ActionJSONReply) ProtoMessage()    {}
func (*ActionJSONReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{22}
}

func (m *ActionJSONReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionJSONReply.Unmarshal(m, b)
}
func (m *ActionJSONReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionJSONReply.Marshal(b, m, deterministic)
}
func (m *ActionJSONReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionJSONReply.Merge(m, src)
}
func (m *ActionJSONReply) XXX_Size() int {
	return xxx_messageInfo_ActionJSONReply.Size(m)
}
func (m *ActionJSONReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionJSONReply.DiscardUnknown(m)
}

var xxx_messageInfo_ActionJSONReply proto.InternalMessageInfo

func (m *ActionJSONReply) GetResReqId() int64 {
	if m != nil {
		return m.ResReqId
	}
	return 0
}

func (m *ActionJSONReply) GetYangjson() string {
	if m != nil {
		return m.Yangjson
	}
	return ""
}

func (m *ActionJSONReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type GetProtoFileArgs struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	YangPath             string   `protobuf:"bytes,2,opt,name=yangPath,proto3" json:"yangPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProtoFileArgs) Reset()         { *m = GetProtoFileArgs{} }
func (m *GetProtoFileArgs) String() string { return proto.CompactTextString(m) }
func (*GetProtoFileArgs) ProtoMessage()    {}
func (*GetProtoFileArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{23}
}

func (m *GetProtoFileArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProtoFileArgs.Unmarshal(m, b)
}
func (m *GetProtoFileArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProtoFileArgs.Marshal(b, m, deterministic)
}
func (m *GetProtoFileArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProtoFileArgs.Merge(m, src)
}
func (m *GetProtoFileArgs) XXX_Size() int {
	return xxx_messageInfo_GetProtoFileArgs.Size(m)
}
func (m *GetProtoFileArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProtoFileArgs.DiscardUnknown(m)
}

var xxx_messageInfo_GetProtoFileArgs proto.InternalMessageInfo

func (m *GetProtoFileArgs) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *GetProtoFileArgs) GetYangPath() string {
	if m != nil {
		return m.YangPath
	}
	return ""
}

type GetProtoFileReply struct {
	ReqId                int64    `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	ProtoContent         string   `protobuf:"bytes,2,opt,name=protoContent,proto3" json:"protoContent,omitempty"`
	Errors               string   `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProtoFileReply) Reset()         { *m = GetProtoFileReply{} }
func (m *GetProtoFileReply) String() string { return proto.CompactTextString(m) }
func (*GetProtoFileReply) ProtoMessage()    {}
func (*GetProtoFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7c1e2e2e74087, []int{24}
}

func (m *GetProtoFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProtoFileReply.Unmarshal(m, b)
}
func (m *GetProtoFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProtoFileReply.Marshal(b, m, deterministic)
}
func (m *GetProtoFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProtoFileReply.Merge(m, src)
}
func (m *GetProtoFileReply) XXX_Size() int {
	return xxx_messageInfo_GetProtoFileReply.Size(m)
}
func (m *GetProtoFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProtoFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetProtoFileReply proto.InternalMessageInfo

func (m *GetProtoFileReply) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *GetProtoFileReply) GetProtoContent() string {
	if m != nil {
		return m.ProtoContent
	}
	return ""
}

func (m *GetProtoFileReply) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func init() {
	proto.RegisterEnum("IOSXRExtensibleManagabilityService.CommitResult", CommitResult_name, CommitResult_value)
	proto.RegisterType((*ConfigGetArgs)(nil), "IOSXRExtensibleManagabilityService.ConfigGetArgs")
	proto.RegisterType((*ConfigGetReply)(nil), "IOSXRExtensibleManagabilityService.ConfigGetReply")
	proto.RegisterType((*GetOperArgs)(nil), "IOSXRExtensibleManagabilityService.GetOperArgs")
	proto.RegisterType((*GetOperReply)(nil), "IOSXRExtensibleManagabilityService.GetOperReply")
	proto.RegisterType((*ConfigArgs)(nil), "IOSXRExtensibleManagabilityService.ConfigArgs")
	proto.RegisterType((*ConfigReply)(nil), "IOSXRExtensibleManagabilityService.ConfigReply")
	proto.RegisterType((*CliConfigArgs)(nil), "IOSXRExtensibleManagabilityService.CliConfigArgs")
	proto.RegisterType((*CliConfigReply)(nil), "IOSXRExtensibleManagabilityService.CliConfigReply")
	proto.RegisterType((*CommitReplaceArgs)(nil), "IOSXRExtensibleManagabilityService.CommitReplaceArgs")
	proto.RegisterType((*CommitReplaceReply)(nil), "IOSXRExtensibleManagabilityService.CommitReplaceReply")
	proto.RegisterType((*CommitMsg)(nil), "IOSXRExtensibleManagabilityService.CommitMsg")
	proto.RegisterType((*CommitArgs)(nil), "IOSXRExtensibleManagabilityService.CommitArgs")
	proto.RegisterType((*CommitReply)(nil), "IOSXRExtensibleManagabilityService.CommitReply")
	proto.RegisterType((*DiscardChangesArgs)(nil), "IOSXRExtensibleManagabilityService.DiscardChangesArgs")
	proto.RegisterType((*DiscardChangesReply)(nil), "IOSXRExtensibleManagabilityService.DiscardChangesReply")
	proto.RegisterType((*ShowCmdArgs)(nil), "IOSXRExtensibleManagabilityService.ShowCmdArgs")
	proto.RegisterType((*ShowCmdTextReply)(nil), "IOSXRExtensibleManagabilityService.ShowCmdTextReply")
	proto.RegisterType((*ShowCmdJSONReply)(nil), "IOSXRExtensibleManagabilityService.ShowCmdJSONReply")
	proto.RegisterType((*QOSMarking)(nil), "IOSXRExtensibleManagabilityService.QOSMarking")
	proto.RegisterType((*CreateSubsArgs)(nil), "IOSXRExtensibleManagabilityService.CreateSubsArgs")
	proto.RegisterType((*CreateSubsReply)(nil), "IOSXRExtensibleManagabilityService.CreateSubsReply")
	proto.RegisterType((*ActionJSONArgs)(nil), "IOSXRExtensibleManagabilityService.ActionJSONArgs")
	proto.RegisterType((*ActionJSONReply)(nil), "IOSXRExtensibleManagabilityService.ActionJSONReply")
	proto.RegisterType((*GetProtoFileArgs)(nil), "IOSXRExtensibleManagabilityService.GetProtoFileArgs")
	proto.RegisterType((*GetProtoFileReply)(nil), "IOSXRExtensibleManagabilityService.GetProtoFileReply")
}

func init() { proto.RegisterFile("mdt_grpc_dialin.proto", fileDescriptor_84c7c1e2e2e74087) }

var fileDescriptor_84c7c1e2e2e74087 = []byte{
	// 961 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xc6, 0x69, 0x1a, 0x1f, 0xdb, 0xa9, 0x33, 0x14, 0x64, 0x59, 0x08, 0x45, 0x23, 0x54,
	0x45, 0x7d, 0x30, 0x25, 0x69, 0xe0, 0x01, 0x09, 0x61, 0x6d, 0x52, 0xd7, 0x15, 0x89, 0xc3, 0xb8,
	0x12, 0xf0, 0x40, 0xc3, 0x78, 0x77, 0xba, 0x19, 0xd8, 0x5b, 0x66, 0xc7, 0x25, 0x79, 0xe0, 0xf2,
	0x00, 0x0f, 0xfc, 0x2d, 0x5e, 0xf8, 0x5b, 0x68, 0x66, 0xef, 0x01, 0xc7, 0xbb, 0x29, 0xc9, 0xdb,
	0x9e, 0xb1, 0xcf, 0x77, 0xbe, 0x73, 0xd9, 0xf9, 0xce, 0xc2, 0xbb, 0x9e, 0x2d, 0x4f, 0x1d, 0x11,
	0x5a, 0xa7, 0x36, 0xa7, 0x2e, 0xf7, 0x07, 0xa1, 0x08, 0x64, 0x80, 0xf0, 0x78, 0x32, 0xfd, 0x86,
	0x1c, 0x5e, 0x48, 0xe6, 0x47, 0x7c, 0xe6, 0xb2, 0x23, 0xea, 0x53, 0x87, 0xce, 0xb8, 0xcb, 0xe5,
	0xe5, 0x94, 0x89, 0x37, 0xdc, 0x62, 0x78, 0x0c, 0x1d, 0x33, 0xf0, 0x5f, 0x73, 0x67, 0xc4, 0xe4,
	0x50, 0x38, 0x11, 0x7a, 0x08, 0xf7, 0x08, 0x3b, 0x1f, 0xdb, 0x3d, 0x63, 0xdb, 0xd8, 0x69, 0x90,
	0xd8, 0x40, 0x18, 0xda, 0x97, 0xd4, 0x77, 0x42, 0x2a, 0xcf, 0x7e, 0x88, 0x02, 0xbf, 0xb7, 0xba,
	0x6d, 0xec, 0x34, 0x49, 0xe9, 0x0c, 0x7f, 0x0f, 0x9b, 0x19, 0x14, 0x61, 0xa1, 0x7b, 0x89, 0xfa,
	0xb0, 0x41, 0x58, 0x54, 0x84, 0xcb, 0x6c, 0xf5, 0x9b, 0xf2, 0x2e, 0xa0, 0x65, 0x36, 0x7a, 0x0f,
	0xd6, 0x99, 0x10, 0x81, 0x88, 0x7a, 0x0d, 0xfd, 0x4b, 0x62, 0xe1, 0x11, 0xb4, 0x46, 0x4c, 0x4e,
	0x42, 0x26, 0xde, 0x92, 0xea, 0x2b, 0x68, 0x27, 0x40, 0xb7, 0x43, 0xf4, 0x77, 0x03, 0x20, 0xae,
	0xc5, 0x35, 0x44, 0xaf, 0x03, 0x7e, 0x1f, 0x9a, 0xda, 0x5f, 0x78, 0xcc, 0xd6, 0xd8, 0x1b, 0x24,
	0x3f, 0x40, 0x8f, 0x92, 0x4a, 0x0b, 0xef, 0x25, 0xf7, 0x58, 0x30, 0x97, 0xbd, 0xb5, 0x6d, 0x63,
	0xa7, 0x43, 0xae, 0x9c, 0xe2, 0xef, 0xa0, 0x15, 0xb3, 0x58, 0x9e, 0x65, 0x9e, 0xc9, 0x6a, 0x31,
	0x13, 0xe5, 0x63, 0x06, 0x9e, 0xc7, 0xe5, 0xf8, 0x40, 0xf3, 0xe8, 0x90, 0xcc, 0xc6, 0x3f, 0x43,
	0xc7, 0x74, 0xf9, 0xd2, 0x3c, 0xbb, 0xd0, 0xb0, 0x5c, 0x9e, 0xe0, 0xaa, 0xc7, 0xff, 0x29, 0x3b,
	0x35, 0x6f, 0x69, 0xf8, 0xdb, 0x49, 0xf0, 0x6b, 0xd8, 0x8a, 0x9f, 0x15, 0x3c, 0xb5, 0x58, 0xad,
	0x24, 0x8b, 0xed, 0x6d, 0x94, 0xdb, 0x8b, 0x9f, 0x03, 0x2a, 0x01, 0xdf, 0x98, 0x3e, 0xfe, 0x4c,
	0x95, 0x52, 0x21, 0x1d, 0x45, 0x8e, 0xa2, 0xe6, 0xd2, 0x19, 0x73, 0xb5, 0x77, 0x93, 0xc4, 0x06,
	0xea, 0xc1, 0x7d, 0x2b, 0xf0, 0x3c, 0xe6, 0xcb, 0xc4, 0x37, 0x35, 0xf1, 0xe7, 0x6a, 0x4a, 0x95,
	0xf3, 0xf5, 0x53, 0x9a, 0xd5, 0x67, 0xf5, 0x4a, 0x7d, 0x86, 0x6a, 0xbe, 0xd2, 0x34, 0x6e, 0xc6,
	0xff, 0x31, 0xa0, 0x03, 0x1e, 0x59, 0x54, 0xd8, 0xe6, 0x19, 0xf5, 0x1d, 0x16, 0x2d, 0xa6, 0x82,
	0xc7, 0xf0, 0x4e, 0xf9, 0xbf, 0x37, 0x0f, 0xbb, 0x0f, 0xad, 0xe9, 0x59, 0xf0, 0x93, 0xe9, 0xd9,
	0x75, 0x7a, 0x8a, 0x5f, 0x41, 0x37, 0x71, 0x7b, 0xc9, 0x2e, 0xaa, 0x65, 0x1d, 0xcc, 0x65, 0x38,
	0x4f, 0x2b, 0x9f, 0x58, 0x0b, 0xef, 0x8d, 0xd7, 0x19, 0xfe, 0x8b, 0xe9, 0xe4, 0x78, 0x39, 0xfe,
	0x07, 0x00, 0x6a, 0x9e, 0x4a, 0x31, 0x0a, 0x27, 0x0b, 0xe3, 0x3c, 0x02, 0xf8, 0x6a, 0x32, 0x3d,
	0xa2, 0xe2, 0x47, 0xee, 0x3b, 0x6a, 0x40, 0xbc, 0xf8, 0x51, 0x07, 0xe8, 0x90, 0xd4, 0xc4, 0x7f,
	0x19, 0xb0, 0x69, 0x0a, 0x46, 0x25, 0x9b, 0xce, 0x67, 0xd7, 0xb4, 0x46, 0x07, 0xf2, 0xad, 0xc0,
	0x66, 0x9a, 0x44, 0x83, 0x24, 0x96, 0x22, 0x1f, 0xcd, 0x67, 0xdc, 0x8e, 0xa4, 0x48, 0x5f, 0x82,
	0xd4, 0x46, 0x5f, 0x40, 0xe3, 0x3c, 0x88, 0xf4, 0xcb, 0xdd, 0xda, 0x1d, 0x0c, 0x96, 0x8b, 0xd5,
	0x20, 0xe7, 0x4c, 0x94, 0x2b, 0xfa, 0x10, 0x3a, 0x8a, 0x97, 0x25, 0x78, 0x28, 0x79, 0xe0, 0x47,
	0xbd, 0x7b, 0xdb, 0x8d, 0x9d, 0x26, 0x29, 0x1f, 0xe2, 0x6f, 0xe1, 0x41, 0x9e, 0xc3, 0xf2, 0x9a,
	0x22, 0x58, 0xb3, 0xa9, 0xa4, 0x3a, 0x91, 0x36, 0xd1, 0xcf, 0x0b, 0xeb, 0xf8, 0x02, 0x36, 0x87,
	0x96, 0x8a, 0xa2, 0xda, 0xf5, 0x96, 0x9a, 0x44, 0xe1, 0x41, 0x8e, 0x75, 0x3b, 0xb2, 0x74, 0x00,
	0xdd, 0x11, 0x93, 0x27, 0x6a, 0x39, 0x78, 0xc6, 0xdd, 0xec, 0x3a, 0x13, 0x45, 0xc2, 0xa2, 0x88,
	0x7e, 0x42, 0xe5, 0x59, 0x11, 0x5d, 0xd9, 0x98, 0xc1, 0x56, 0x11, 0x25, 0xa6, 0xfa, 0xdf, 0x30,
	0x18, 0xda, 0x7a, 0x15, 0x31, 0x03, 0x5f, 0xe6, 0xf7, 0x4f, 0xe9, 0x6c, 0x11, 0xd9, 0xc7, 0x7b,
	0xd0, 0x4e, 0x2f, 0x97, 0x68, 0xee, 0x4a, 0x04, 0xb0, 0x6e, 0x3e, 0x1f, 0x1e, 0x8f, 0x0e, 0xbb,
	0x2b, 0xa8, 0x03, 0xcd, 0xe3, 0xc9, 0x69, 0x62, 0x1a, 0x68, 0x03, 0xd6, 0x9e, 0x0d, 0xc7, 0x5f,
	0x76, 0x57, 0x77, 0xff, 0x06, 0xd8, 0x74, 0xc8, 0x89, 0x19, 0xab, 0x82, 0x12, 0x78, 0xf4, 0x06,
	0x9a, 0x23, 0x26, 0xe3, 0x03, 0xf4, 0x71, 0x95, 0x31, 0x2b, 0x2d, 0x44, 0xfd, 0xdd, 0x5a, 0x2e,
	0xba, 0x1a, 0x78, 0xe5, 0x89, 0x81, 0x42, 0x68, 0x1d, 0x31, 0xe1, 0xb0, 0x24, 0xf2, 0xa0, 0x3a,
	0x8c, 0x0e, 0xfb, 0x51, 0xf5, 0xff, 0x27, 0x31, 0xd1, 0x39, 0xb4, 0x0f, 0x98, 0xcb, 0xe4, 0x1d,
	0x86, 0x14, 0xd0, 0x49, 0x24, 0xec, 0xee, 0x62, 0x4a, 0x68, 0x66, 0xba, 0x5f, 0xb1, 0xa1, 0xc5,
	0x2d, 0xa5, 0x62, 0x43, 0x4b, 0x9b, 0x05, 0x5e, 0x41, 0xbf, 0x19, 0x6a, 0x53, 0x2e, 0x68, 0x36,
	0xda, 0xaf, 0x46, 0xfd, 0xca, 0xfe, 0xd0, 0xff, 0xa4, 0xb6, 0x5b, 0xa1, 0xbf, 0xf1, 0x79, 0xbd,
	0x5a, 0xa7, 0x02, 0x5f, 0xb5, 0xd6, 0x99, 0xa0, 0xe3, 0x15, 0xf4, 0xa7, 0x01, 0x0f, 0xe3, 0x68,
	0x65, 0xe5, 0x45, 0x95, 0xb2, 0xf8, 0xb7, 0xb2, 0xf7, 0x3f, 0xad, 0xef, 0x97, 0x72, 0x09, 0xe1,
	0x7e, 0xb2, 0xb4, 0xa3, 0x4a, 0x99, 0x14, 0x3e, 0x15, 0xfa, 0x4f, 0x6a, 0x38, 0xe4, 0xaf, 0xf0,
	0x25, 0x40, 0xae, 0x1c, 0xa8, 0xda, 0xdc, 0x94, 0xd4, 0xb2, 0xbf, 0x57, 0xcf, 0x27, 0x0f, 0xfd,
	0xab, 0xfe, 0x42, 0xc9, 0x2e, 0x59, 0xf4, 0xb4, 0x62, 0x02, 0xa5, 0xcb, 0xbd, 0xbf, 0x5f, 0xd7,
	0x2b, 0x23, 0xb0, 0xfb, 0x47, 0x03, 0x36, 0xd4, 0x4d, 0x7a, 0x78, 0xc1, 0x2c, 0xf4, 0x0b, 0x6c,
	0x15, 0xf6, 0x9e, 0x49, 0xbc, 0x5c, 0x54, 0x6a, 0x42, 0x61, 0xcb, 0xea, 0x3f, 0xad, 0xe1, 0x90,
	0xed, 0x57, 0xba, 0x1a, 0x79, 0x7c, 0x25, 0x8e, 0x77, 0x11, 0x3f, 0x13, 0xe1, 0x74, 0x10, 0x72,
	0x6d, 0xae, 0x36, 0x08, 0xe5, 0xbd, 0xa0, 0xda, 0x20, 0x5c, 0xd1, 0x7f, 0x15, 0x7a, 0xb6, 0xae,
	0xc5, 0x72, 0xef, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xcd, 0x2d, 0x2b, 0xe4, 0x0f, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GRPCConfigOperClient is the client API for GRPCConfigOper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCConfigOperClient interface {
	// Configuration related commands
	GetConfig(ctx context.Context, in *ConfigGetArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetConfigClient, error)
	MergeConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	DeleteConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	ReplaceConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error)
	CliConfig(ctx context.Context, in *CliConfigArgs, opts ...grpc.CallOption) (*CliConfigReply, error)
	CommitReplace(ctx context.Context, in *CommitReplaceArgs, opts ...grpc.CallOption) (*CommitReplaceReply, error)
	// Do we need implicit or explicit commit
	//
	CommitConfig(ctx context.Context, in *CommitArgs, opts ...grpc.CallOption) (*CommitReply, error)
	ConfigDiscardChanges(ctx context.Context, in *DiscardChangesArgs, opts ...grpc.CallOption) (*DiscardChangesReply, error)
	// Get only returns oper data
	//
	GetOper(ctx context.Context, in *GetOperArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetOperClient, error)
	// Get Telemetry Data
	CreateSubs(ctx context.Context, in *CreateSubsArgs, opts ...grpc.CallOption) (GRPCConfigOper_CreateSubsClient, error)
	// Get Proto File
	GetProtoFile(ctx context.Context, in *GetProtoFileArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetProtoFileClient, error)
}

type gRPCConfigOperClient struct {
	cc *grpc.ClientConn
}

func NewGRPCConfigOperClient(cc *grpc.ClientConn) GRPCConfigOperClient {
	return &gRPCConfigOperClient{cc}
}

func (c *gRPCConfigOperClient) GetConfig(ctx context.Context, in *ConfigGetArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[0], "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetConfigClient interface {
	Recv() (*ConfigGetReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetConfigClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetConfigClient) Recv() (*ConfigGetReply, error) {
	m := new(ConfigGetReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) MergeConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) DeleteConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) ReplaceConfig(ctx context.Context, in *ConfigArgs, opts ...grpc.CallOption) (*ConfigReply, error) {
	out := new(ConfigReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CliConfig(ctx context.Context, in *CliConfigArgs, opts ...grpc.CallOption) (*CliConfigReply, error) {
	out := new(CliConfigReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CommitReplace(ctx context.Context, in *CommitReplaceArgs, opts ...grpc.CallOption) (*CommitReplaceReply, error) {
	out := new(CommitReplaceReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) CommitConfig(ctx context.Context, in *CommitArgs, opts ...grpc.CallOption) (*CommitReply, error) {
	out := new(CommitReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) ConfigDiscardChanges(ctx context.Context, in *DiscardChangesArgs, opts ...grpc.CallOption) (*DiscardChangesReply, error) {
	out := new(DiscardChangesReply)
	err := c.cc.Invoke(ctx, "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCConfigOperClient) GetOper(ctx context.Context, in *GetOperArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetOperClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[1], "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetOper", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetOperClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetOperClient interface {
	Recv() (*GetOperReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetOperClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetOperClient) Recv() (*GetOperReply, error) {
	m := new(GetOperReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) CreateSubs(ctx context.Context, in *CreateSubsArgs, opts ...grpc.CallOption) (GRPCConfigOper_CreateSubsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[2], "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CreateSubs", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperCreateSubsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_CreateSubsClient interface {
	Recv() (*CreateSubsReply, error)
	grpc.ClientStream
}

type gRPCConfigOperCreateSubsClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperCreateSubsClient) Recv() (*CreateSubsReply, error) {
	m := new(CreateSubsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCConfigOperClient) GetProtoFile(ctx context.Context, in *GetProtoFileArgs, opts ...grpc.CallOption) (GRPCConfigOper_GetProtoFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCConfigOper_serviceDesc.Streams[3], "/IOSXRExtensibleManagabilityService.gRPCConfigOper/GetProtoFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCConfigOperGetProtoFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCConfigOper_GetProtoFileClient interface {
	Recv() (*GetProtoFileReply, error)
	grpc.ClientStream
}

type gRPCConfigOperGetProtoFileClient struct {
	grpc.ClientStream
}

func (x *gRPCConfigOperGetProtoFileClient) Recv() (*GetProtoFileReply, error) {
	m := new(GetProtoFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPCConfigOperServer is the server API for GRPCConfigOper service.
type GRPCConfigOperServer interface {
	// Configuration related commands
	GetConfig(*ConfigGetArgs, GRPCConfigOper_GetConfigServer) error
	MergeConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	DeleteConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	ReplaceConfig(context.Context, *ConfigArgs) (*ConfigReply, error)
	CliConfig(context.Context, *CliConfigArgs) (*CliConfigReply, error)
	CommitReplace(context.Context, *CommitReplaceArgs) (*CommitReplaceReply, error)
	// Do we need implicit or explicit commit
	//
	CommitConfig(context.Context, *CommitArgs) (*CommitReply, error)
	ConfigDiscardChanges(context.Context, *DiscardChangesArgs) (*DiscardChangesReply, error)
	// Get only returns oper data
	//
	GetOper(*GetOperArgs, GRPCConfigOper_GetOperServer) error
	// Get Telemetry Data
	CreateSubs(*CreateSubsArgs, GRPCConfigOper_CreateSubsServer) error
	// Get Proto File
	GetProtoFile(*GetProtoFileArgs, GRPCConfigOper_GetProtoFileServer) error
}

func RegisterGRPCConfigOperServer(s *grpc.Server, srv GRPCConfigOperServer) {
	s.RegisterService(&_GRPCConfigOper_serviceDesc, srv)
}

func _GRPCConfigOper_GetConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigGetArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetConfig(m, &gRPCConfigOperGetConfigServer{stream})
}

type GRPCConfigOper_GetConfigServer interface {
	Send(*ConfigGetReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetConfigServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetConfigServer) Send(m *ConfigGetReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_MergeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).MergeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/MergeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).MergeConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/DeleteConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).DeleteConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_ReplaceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).ReplaceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ReplaceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).ReplaceConfig(ctx, req.(*ConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CliConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CliConfigArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CliConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CliConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CliConfig(ctx, req.(*CliConfigArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CommitReplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitReplaceArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CommitReplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitReplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CommitReplace(ctx, req.(*CommitReplaceArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_CommitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).CommitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/CommitConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).CommitConfig(ctx, req.(*CommitArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_ConfigDiscardChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardChangesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCConfigOperServer).ConfigDiscardChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IOSXRExtensibleManagabilityService.gRPCConfigOper/ConfigDiscardChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCConfigOperServer).ConfigDiscardChanges(ctx, req.(*DiscardChangesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCConfigOper_GetOper_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetOperArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetOper(m, &gRPCConfigOperGetOperServer{stream})
}

type GRPCConfigOper_GetOperServer interface {
	Send(*GetOperReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetOperServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetOperServer) Send(m *GetOperReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_CreateSubs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateSubsArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).CreateSubs(m, &gRPCConfigOperCreateSubsServer{stream})
}

type GRPCConfigOper_CreateSubsServer interface {
	Send(*CreateSubsReply) error
	grpc.ServerStream
}

type gRPCConfigOperCreateSubsServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperCreateSubsServer) Send(m *CreateSubsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCConfigOper_GetProtoFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetProtoFileArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCConfigOperServer).GetProtoFile(m, &gRPCConfigOperGetProtoFileServer{stream})
}

type GRPCConfigOper_GetProtoFileServer interface {
	Send(*GetProtoFileReply) error
	grpc.ServerStream
}

type gRPCConfigOperGetProtoFileServer struct {
	grpc.ServerStream
}

func (x *gRPCConfigOperGetProtoFileServer) Send(m *GetProtoFileReply) error {
	return x.ServerStream.SendMsg(m)
}

var _GRPCConfigOper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IOSXRExtensibleManagabilityService.gRPCConfigOper",
	HandlerType: (*GRPCConfigOperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergeConfig",
			Handler:    _GRPCConfigOper_MergeConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _GRPCConfigOper_DeleteConfig_Handler,
		},
		{
			MethodName: "ReplaceConfig",
			Handler:    _GRPCConfigOper_ReplaceConfig_Handler,
		},
		{
			MethodName: "CliConfig",
			Handler:    _GRPCConfigOper_CliConfig_Handler,
		},
		{
			MethodName: "CommitReplace",
			Handler:    _GRPCConfigOper_CommitReplace_Handler,
		},
		{
			MethodName: "CommitConfig",
			Handler:    _GRPCConfigOper_CommitConfig_Handler,
		},
		{
			MethodName: "ConfigDiscardChanges",
			Handler:    _GRPCConfigOper_ConfigDiscardChanges_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConfig",
			Handler:       _GRPCConfigOper_GetConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOper",
			Handler:       _GRPCConfigOper_GetOper_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateSubs",
			Handler:       _GRPCConfigOper_CreateSubs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetProtoFile",
			Handler:       _GRPCConfigOper_GetProtoFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mdt_grpc_dialin.proto",
}

// GRPCExecClient is the client API for GRPCExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCExecClient interface {
	// Exec commands
	ShowCmdTextOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdTextOutputClient, error)
	ShowCmdJSONOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdJSONOutputClient, error)
	ActionJSON(ctx context.Context, in *ActionJSONArgs, opts ...grpc.CallOption) (GRPCExec_ActionJSONClient, error)
}

type gRPCExecClient struct {
	cc *grpc.ClientConn
}

func NewGRPCExecClient(cc *grpc.ClientConn) GRPCExecClient {
	return &gRPCExecClient{cc}
}

func (c *gRPCExecClient) ShowCmdTextOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdTextOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCExec_serviceDesc.Streams[0], "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdTextOutput", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecShowCmdTextOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ShowCmdTextOutputClient interface {
	Recv() (*ShowCmdTextReply, error)
	grpc.ClientStream
}

type gRPCExecShowCmdTextOutputClient struct {
	grpc.ClientStream
}

func (x *gRPCExecShowCmdTextOutputClient) Recv() (*ShowCmdTextReply, error) {
	m := new(ShowCmdTextReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCExecClient) ShowCmdJSONOutput(ctx context.Context, in *ShowCmdArgs, opts ...grpc.CallOption) (GRPCExec_ShowCmdJSONOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCExec_serviceDesc.Streams[1], "/IOSXRExtensibleManagabilityService.gRPCExec/ShowCmdJSONOutput", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecShowCmdJSONOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ShowCmdJSONOutputClient interface {
	Recv() (*ShowCmdJSONReply, error)
	grpc.ClientStream
}

type gRPCExecShowCmdJSONOutputClient struct {
	grpc.ClientStream
}

func (x *gRPCExecShowCmdJSONOutputClient) Recv() (*ShowCmdJSONReply, error) {
	m := new(ShowCmdJSONReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gRPCExecClient) ActionJSON(ctx context.Context, in *ActionJSONArgs, opts ...grpc.CallOption) (GRPCExec_ActionJSONClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GRPCExec_serviceDesc.Streams[2], "/IOSXRExtensibleManagabilityService.gRPCExec/ActionJSON", opts...)
	if err != nil {
		return nil, err
	}
	x := &gRPCExecActionJSONClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GRPCExec_ActionJSONClient interface {
	Recv() (*ActionJSONReply, error)
	grpc.ClientStream
}

type gRPCExecActionJSONClient struct {
	grpc.ClientStream
}

func (x *gRPCExecActionJSONClient) Recv() (*ActionJSONReply, error) {
	m := new(ActionJSONReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GRPCExecServer is the server API for GRPCExec service.
type GRPCExecServer interface {
	// Exec commands
	ShowCmdTextOutput(*ShowCmdArgs, GRPCExec_ShowCmdTextOutputServer) error
	ShowCmdJSONOutput(*ShowCmdArgs, GRPCExec_ShowCmdJSONOutputServer) error
	ActionJSON(*ActionJSONArgs, GRPCExec_ActionJSONServer) error
}

func RegisterGRPCExecServer(s *grpc.Server, srv GRPCExecServer) {
	s.RegisterService(&_GRPCExec_serviceDesc, srv)
}

func _GRPCExec_ShowCmdTextOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShowCmdArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ShowCmdTextOutput(m, &gRPCExecShowCmdTextOutputServer{stream})
}

type GRPCExec_ShowCmdTextOutputServer interface {
	Send(*ShowCmdTextReply) error
	grpc.ServerStream
}

type gRPCExecShowCmdTextOutputServer struct {
	grpc.ServerStream
}

func (x *gRPCExecShowCmdTextOutputServer) Send(m *ShowCmdTextReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCExec_ShowCmdJSONOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ShowCmdArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ShowCmdJSONOutput(m, &gRPCExecShowCmdJSONOutputServer{stream})
}

type GRPCExec_ShowCmdJSONOutputServer interface {
	Send(*ShowCmdJSONReply) error
	grpc.ServerStream
}

type gRPCExecShowCmdJSONOutputServer struct {
	grpc.ServerStream
}

func (x *gRPCExecShowCmdJSONOutputServer) Send(m *ShowCmdJSONReply) error {
	return x.ServerStream.SendMsg(m)
}

func _GRPCExec_ActionJSON_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionJSONArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCExecServer).ActionJSON(m, &gRPCExecActionJSONServer{stream})
}

type GRPCExec_ActionJSONServer interface {
	Send(*ActionJSONReply) error
	grpc.ServerStream
}

type gRPCExecActionJSONServer struct {
	grpc.ServerStream
}

func (x *gRPCExecActionJSONServer) Send(m *ActionJSONReply) error {
	return x.ServerStream.SendMsg(m)
}

var _GRPCExec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IOSXRExtensibleManagabilityService.gRPCExec",
	HandlerType: (*GRPCExecServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ShowCmdTextOutput",
			Handler:       _GRPCExec_ShowCmdTextOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ShowCmdJSONOutput",
			Handler:       _GRPCExec_ShowCmdJSONOutput_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ActionJSON",
			Handler:       _GRPCExec_ActionJSON_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mdt_grpc_dialin.proto",
}
